# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://genevalytics.github.io'
baseurl: ''
title: 'Genevalytics'
description: 'This is my new website'
permalink: pretty
logo: "/assets/files/genevalytics_logo.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Events
  url: /events/
- title: Members
  url: /members/
- title: Contact
  url: /contact/
# - title: Blog
#   url: /blog/


# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    #feature_image: "https://picsum.photos/2560/600?image=866"
  members:
    title: Members
    output: true
    permalink: /members/:name/
    description: "Meet the Team"
    feature_text: |
      Meet the Team
  events:
    title: Events
    output: true
    permalink: /events/:name/
    description: "Events"
    feature_text: |
      Upcoming and Past Events
  announcements:
    title: Annoucements
    output: true
    permalink: /announcements/:name/
    description: "Announcements"
    feature_text: |
      Annoucements

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: page # Set the default layout for pages